### ISSUE TITLE
Fix compilation on Windows (at least)

### ISSUE THREAD

**Issue by mohits** [klaxit/fast-polylines#20]
Hi! I tried to install the gem on Ruby 2.6.6 on Windows and it continuously failed to build due to an error with finding the typdef for uint. I tried to see if I could something obvious (e.g. #include <types.h>) but that didn't really work.

I read through the code and added the only 1 line change that is needed to make the code work:
typedef unsigned int uint;
to the C file.

I intended to raise the pull request to my own fork first, but I accidentally did open it here. Please feel free to reject it, or accept it if you think it would help.

The gist at: https://gist.github.com/mohits/3b22d70af5f4f36963a4a5f95041c41d shows the running after the change.

Let me know if I can assist in any way :) on this. 
See also Pull Request: #19 

Have a good day!

**Comment by mohits** [comment]
Once we merge #19  and #23, this will be good to go!

**Comment by BuonOmo** [comment]
Maybe i should've added my comment https://github.com/klaxit/fast-polylines/issues/21#issuecomment-732039308 here:

> @mohits I'm thinking about adding a note about that on the readme. I'll do so once everything is merged. No need for a manual test on pre-release, I'll do a patch and include the fact that windows compilation is not guaranteed since we cannot test it in an automated fashion. Could I add your name in that paragraph to say that you should be mentioned in windows related issue ?
> 
> In the meantime, I'll wait for the last fixes to integrate every PRs you made ! Thanks again for the journey you made :)
