### ISSUE TITLE
Problem with higher-precision lines

### ISSUE THREAD

**Issue by will-r** [klaxit/fast-polylines#25]
Hi. For some lines at higher precision I'm finding that while fast-polylines agrees with itself, it doesn't agree with the javascript libraries. Have you encountered this?

```
points = [[53.05863, -3.81751], [53.05859, -3.81737]]
path = FastPolylines.encode(points, 8)
    # => "otdcg{HnlfcwU~xF_jZ"
FastPolylines.decode(path, 8)
    # => [[53.05863, -3.81751], [53.05859, -3.81737]]

import { decode } from "@googlemaps/polyline-codec";
decode("otdcg{HnlfcwU~xF_jZ", 8);
  # => [[10.10895704,-3.81751],[10.10891704,-3.81737]]
```

I get the same wrong decode result with @mapbox/polyline, but interestingly the old Polylines library decodes your path string correctly.

**Comment by BuonOmo** [comment]
@will-r that is weird, the results are completely different... Did you find any updated spec that @mapbox/polyline could be using?

**Comment by BuonOmo** [comment]
@will-r closing now, we could reopen the issue if you bring more information/a reproducible example!
